# Generated by Django 5.1 on 2024-08-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_deposite_withdraw_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdrawal', 'Withdrawal')], default='Deposite', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdrawal', 'Withdrawal')], default='Withdrawal', max_length=20),
        ),
    ]
