# Generated by Django 5.1 on 2024-08-14 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_alter_deposite_transaction_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposite',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw')], default='Deposite', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw')], default='Withdraw', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to=settings.AUTH_USER_MODEL),
        ),
    ]
