# Generated by Django 5.1 on 2024-08-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_deposite_transaction_type_alter_deposite_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='test',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('test', 'test')], default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposite',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('test', 'test')], default='Deposite', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw'), ('test', 'test')], default='Withdraw', max_length=20),
        ),
    ]
