# Generated by Django 5.1 on 2024-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_withdraw_test_alter_deposite_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='test',
        ),
        migrations.AlterField(
            model_name='deposite',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw')], default='Deposite', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_type',
            field=models.CharField(choices=[('Deposite', 'Deposite'), ('Withdraw', 'Withdraw')], default='Withdraw', max_length=20),
        ),
    ]
