# Generated by Django 5.0.6 on 2024-07-04 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_cars_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='brand',
        ),
        migrations.AddField(
            model_name='comment',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='car.cars'),
        ),
    ]
