# Generated by Django 5.0.6 on 2024-07-05 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_remove_comment_brand_comment_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
