# Generated by Django 5.0.6 on 2024-07-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cars_quantity_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
