# Generated by Django 5.0.6 on 2024-07-05 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_cars_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='quantity',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
