# Generated by Django 5.0.6 on 2024-07-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_cars_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='car/media/uploads/'),
        ),
    ]
