# Generated by Django 5.1 on 2024-08-13 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='pet/images/')),
                ('adoption_status', models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted')], default='Available', max_length=10)),
                ('price', models.IntegerField()),
                ('pet_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pet.pettype')),
            ],
        ),
    ]
