# Generated by Django 5.1 on 2024-08-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_pet_age_adoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
