# Generated by Django 5.1 on 2024-08-17 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_alter_pet_age_remove_pet_pet_type_pet_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.pettype'),
        ),
    ]
