# Generated by Django 5.1 on 2024-08-23 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0011_pet_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(upload_to='pet-add-image'),
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pettype'),
            preserve_default=False,
        ),
    ]
