# Generated by Django 5.1 on 2024-08-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0013_alter_pet_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
    ]
