# Generated by Django 5.1 on 2024-08-23 11:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0015_remove_pet_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
