# Generated by Django 5.1 on 2024-08-23 12:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0017_remove_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
