# Generated by Django 5.1 on 2024-08-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0018_pet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=models.FileField(upload_to='pet-add-image'),
        ),
    ]
