# Generated by Django 5.1 on 2024-08-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0020_alter_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet.pettype'),
            preserve_default=False,
        ),
    ]
