# Generated by Django 5.0.6 on 2024-07-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_review_rating_delete_borrowform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.IntegerField(choices=[('BORROW', 1), ('RETURN', 2)], null=True),
        ),
    ]
