# Generated by Django 5.1 on 2024-08-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='customer/images/')),
                ('type', models.CharField(choices=[('pet_sitter', 'PET SITTER'), ('pet_grommer', 'PET GROMMER'), ('pet_doctor', 'PET DOCTOR'), ('pet_manager', 'PET MANAGER')], default='Customer', max_length=30)),
            ],
        ),
    ]
