# Generated by Django 5.1 on 2024-08-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='type',
            field=models.CharField(choices=[('pet_sitter', 'PET SITTER'), ('pet_grommer', 'PET GROMMER'), ('pet_doctor', 'PET DOCTOR'), ('pet_manager', 'PET MANAGER')], max_length=30),
        ),
    ]
