# Generated by Django 5.1 on 2024-08-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_user_alter_customer_user_type'),
        ('pet', '0003_alter_pet_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('✮', '✮'), ('✮✮', '✮✮'), ('✮✮✮', '✮✮✮'), ('✮✮✮✮', '✮✮✮✮'), ('✮✮✮✮✮', '✮✮✮✮✮')], max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
