# Generated by Django 5.0.6 on 2024-07-17 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WithdrawForm',
        ),
    ]
